package com.hotelbooking.hotelbooking.model;

import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


// Marks this class as a JPA entity representing a database table
@Entity

// Lombok annotations to auto-generate getters, setters, constructors
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class BookedRoom {

     // Unique booking ID, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long bookingId;

    // Booking check-in date
    @Column(name = "check_In")
    private LocalDate checkInDate;

    // Booking check-out date
    @Column(name = "check_Out")
    private LocalDate checkOutDate;

    // Full name of the guest making the booking
    @Column(name = "guest_FullName")
    private String guestFullName;

    // Guest's email address
    @Column(name ="guest_Email")
    private String guestEmail;

     // Number of adults in the booking
    @Column(name ="adults")
    private int NumOfAdults;

    // Number of children in the booking
    @Column(name ="children")
    private int NumOfChildren;

    // Total number of guests (calculated as adults + children)
    @Column(name = "total_guest")
    private int totalNumOfGuest;

     // Unique booking confirmation code
    @Column(name = "confirmation_Code")
    private String bookingConfirmationCode;

    // Many-to-one relationship with the Room entity
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id")
    private Room room;


    //get the total number of guests
    // * This method is called whenever the number of adults or children is updated.
    public void calculateTotalNumberofGuest(){
        this.totalNumOfGuest = this.NumOfAdults + NumOfChildren;
    }


    //setter
    public void setNumOfAdults(int NumOfAdults){
        NumOfAdults = NumOfAdults;
        calculateTotalNumberofGuest();
    }

    public void setNumOfChildren(int NumOfChildren){
        NumOfChildren = NumOfChildren;
        calculateTotalNumberofGuest();
    }

    public void setBookingConfirmationCode(String bookingConfirmationCode){
        this.bookingConfirmationCode = bookingConfirmationCode;
    } 

}
