spring.application.name : hotelbooking
server:
    port : 8080


spring: 
    datasource:
      username: root
      password: Nmklop@7799
      url: jdbc:mysql://localhost:3306/hotelbooking
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
       show-sql: true
       hibernate:
          ddl-auto: update
          format_sql: true
    servlet:
      multipart:
       max-file-size: 5MB
       max-request-size: 5MB
       file-size-threshold: 2KB


